### ISSUE TITLE
1.20 🙏🏼 

### ISSUE THREAD

**Issue by jeziqt** [RoverIsADog/InfoHUD#10]
Hi :) I know this isn't an issue but I hope we get an official 1.20 update for this plugin. It's incredibly useful!

**Comment by RoverIsADog** [comment]
This is likely because you are using bukkit. Bukkit doesn't have the proper API to send messages to the actionbar. So, for those users, I have to use NMS and update it everytime minecraft updates. I haven't gotten to that yet.

In the meantime, the plugin will work on 1.20 (and future versions) if you run your server on [spigot](https://www.spigotmc.org/) or [paper](https://papermc.io/) instead of bukkit.

**Comment by RoverIsADog** [comment]
Fixed b6beb18
