### ISSUE TITLE
Request for update

### ISSUE THREAD

**Issue by Strix2102** [RoverIsADog/InfoHUD#12]
Hello, I appreciate how simple and helpful your plugin is but it no longer works now that I've updated my server to 1.20.6. I am also planning to update to 1.21 soon so compatibility for these new versions would be greatly appreciated when you have the time. Thank you!

**Comment by Auriny** [comment]
bump

**Comment by RillSoji** [comment]
Would also really appreciate and update for 1.21+ Our communities love this plugin! <3

**Comment by RoverIsADog** [comment]
Sorry for no updates for a while, I haven't played MC in a while so didn't have the motivation to work on it. I merged the PR that fixed the crash with Paper 1.20.5+ (thx @ade), but I haven't updated NMS yet so it still won't work with Bukkit (currently works with Spigot/Paper).

I spent a lot of time trying to make it work but haven't managed it yet. They're changing NMS way more often nowadays and it's a massive chore to update each time there's an update. I'm likely to stop supporting NMS (aka Bukkit) in the future because maintaining it is becoming harder and harder. If you're still using Bukkit, I recommend switching to Spigot or Paper. The plugin will continue working across updates on Spigot / Paper.
